---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tech-blog-frontend.fullname" . }}-ingress
  labels:
    {{- include "tech-blog-frontend.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/limit-connections: '2'
    nginx.ingress.kubernetes.io/limit-rps: '10'
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "tech-blog-frontend.fullname" . }}-nextjs
            port:
              number: 3000

