apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-blog-frontend.fullname" . }}-nextjs
  labels:
    {{- include "tech-blog-frontend.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "tech-blog-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tech-blog-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "tech-blog-frontend.fullname" . }}-nextjs
        image: {{ .Values.nextjs.image.repository }}:{{ .Values.nextjs.image.tag }}
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: BASE_URL
          value: {{ .Values.backend.url }}
        - name: SITE_URL
          value: https://{{ .Values.domain }}
