name: Playwright Tests
on:
  push:
    branches:
      - 'main'
jobs:
 test:
   timeout-minutes: 60
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
       node-version: '18.14'
   - name: Install dependencies
     run: yarn --frozen-lockfile
   - name: Install Playwright Browsers
     run: yarn playwright install
   - name: Run Playwright tests
     run: yarn test:e2e
  #  - uses: actions/upload-artifact@v2
  #    if: always()
  #    with:
  #      name: playwright-report
  #      path: playwright-report/
  #      retention-days: 30